  
  #https://cloud.google.com/blog/products/devops-sre/software-delivery-pipelines-with-gitlab-cicd-and-cloud-deploy/
  # coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  # artifacts:
  #   paths:
  #     - coverage/
  #   when: always
  #   reports:
  #     junit:
  #       - junit.xml
# .gitlab-ci.yml
stages:
  - lint
  - build
  - push
  - deploy

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  PROJECT: mimetic-retina-450410-q0 #civil-charmer-313017
  LOCATION: europe-west1
  SERVICE: tournament-web-app-dev
  AR_IMAGE: $LOCATION-docker.pkg.dev/$PROJECT/tournament-web/$SERVICE

lint-job:
  image: node:22
  stage: lint
  before_script:
    - corepack enable
    - corepack prepare --activate
    - yarn --version
    - yarn install --immutable
  script:
    - yarn lint

build-job:
  stage: build
  services:
    - docker:24.0.5-dind
  image: docker:git
  before_script:
    - cp ${DEVELOPMENT_ENV_FILE} .env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG --build-arg="name=Cloud Run" --build-arg="COMMIT_SHA=$CI_COMMIT_SHORT_SHA" .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

include:
  - component: gitlab.com/google-gitlab-components/artifact-registry/upload-artifact-registry@0.1.0
    inputs:
      stage: push
      source: $CI_REGISTRY_IMAGE:$IMAGE_TAG
      target: $AR_IMAGE:$IMAGE_TAG

  - component: gitlab.com/google-gitlab-components/cloud-run/deploy-cloud-run@0.1.0
    inputs:
      stage: deploy
      image: $AR_IMAGE:$IMAGE_TAG
      project_id: $PROJECT
      region: $LOCATION
      service: $SERVICE
